### ISSUE TITLE
[Nodes 396/397]

### ISSUE THREAD

**Issue by mikepeon** [MONROE-PROJECT/Maintenance#123]
Nodes don't send heartbeats.
Not in maintenance.
Reboot doesn't fix (but creates maintenance event due to unmet dependencies for metadata-exporter).
Related nodes 394-395 seem to work perfectly.
Eth is connected.

**Comment by mikepeon** [comment]
Also, marvind is using a full CPU in both nodes.

**Comment by relet** [comment]
According to the symptoms, the nodes don't have a certificate.
