### ISSUE TITLE
[Node 376/377] Tracking Issue

### ISSUE THREAD

**Issue by alfs** [MONROE-PROJECT/Maintenance#125]
This node is a mobile node that was tested in the lab (not deployed).
During lab testing with car batteries (2x12 V), the power transformer in the node broke down and passed the input voltage to the output wires.

The two APU's thus received 24 VDC instead of 12 VDC, and stopped functioning.

After opening the two APU's and inspecting the motherboard, there are burn marks near the DC jack.

The APUs and the power converter will be sent to Nextworks for replacement.

**Comment by pgiardina** [comment]
New components have been shipped to KAU for replacement:
- 2x APU2 motherboard + chassis
- 2x mSSD
- 1 WiFi card
- 3 Modem LTE cat-6
- 1 24V-12V DC converter
