### ISSUE TITLE
Node [37/40/41/114/199] send to Nextwork for rebuilding

### ISSUE THREAD

**Issue by ali-safari** [MONROE-PROJECT/Maintenance#126]
During the meeting in Torino these five nodes picked by Giacomo to Nextwork for rebuilding.

**Comment by pgiardina** [comment]
Five new Dual Apu system nodes have been shipped  to POLITO: [592-593, 594-595, 596-597, 598-599, 600-601].
IDs 37, 40, 41, 114, 199 have been marked as RETIRED in the Inventory

**Comment by ali-safari** [comment]
I've just received nodes  [592-593, 594-595, 596-597, 598-599, 600-601] and plugged them.
Could you assign them to Italy?

**Comment by pgiardina** [comment]
All nodes are now assigned to Italy and marked as DEPLOYED

**Comment by relet** [comment]
Certificates are installed.
