### ISSUE TITLE
Release 1.2 "Let it snow, let it snow"

### ISSUE THREAD

**Issue by relet** [MONROE-PROJECT/Maintenance#132]
## Test items
ansible branch 2e6edee484ad048c4a01095f83ef8883bb4bf9f9 (mnr/stage), transition from ef454d82cbb4894a909bfb042863494f92998c5d (mnr/main)

# Packages:

- monroe-experiments_0.1.80-deb8u-20180216x1347-9543e0_amd64.deb
- python-marvin_0.1.76-deb8u-20180216x1358-f282af_all.deb
- python-biteback_0.1.50-deb8u-20180306x1401-e685d4_all.deb
- network-listener_0.1.35-deb8u-20171026x1339-62e769_amd64.deb
- monroe-usb2op_0.1.14-deb8u-20180216x1347-9543e0_amd64.deb
- munin-plugins-monroe_0.1.14-deb8u-20180216x1346-9543e0_amd64.deb
- isc-dhcp-client-cwy2?

# Features:
## Configuration:

- [x] - SCTP modules are enabled and firewall allows SCTP traffic
- [x] - ping target is configured by ansible, using new server rtt.se.monroe-system.eu, can then be configured per project via ansible-variables
- [x] - containers default to 127.0.0.1 (dnsmasq) for DNS lookups
- [x] - dhclient no longer requests (broken) mtu from modems (issues on MC7304)
- [x] - nginx proxies requests to allow modem band locking
- [x] - wifi template for eduroam connections
- [x] - new base images monroe/base:complete
- [x] - use monroe/base:complete as URL_NOOP
- [x] - dnsmasq logging less verbose

## Packages:

- [x] - biteback:
- [x] - cleans stuck processes from atq
- [x] - checks disk usage on /var/tmp and /var/log and inodes on /tmp/
- [x] - checks nginx is running in case of bind fails
- [x] - marvind
- [x] - uses named container monroe-namespace when starting experiments
- [x] - do not redeploy started tasks
- [x] - request timeouts 1 and 5 seconds to the server
- [x] - check for exceeded stop time before checking exceeded start time
- [x] - continuously writes container.log while an experiment is running
- [x] - monroe-experiments
- [x] - use named containers for creating namespace (noop) container
- [x] - adjust mtu on veth interfaces
- [x] - exclude google servers from dnsmasq.monroe.conf
- [x] - duplicate interface mapping detection
- [x] - munin-sensors
- [x] - inventory sensor
- [x] - network-listener
- [x] - removed ICCID validity checks
- [x] - usb2op
- [x] - report heartbeats for non-modem interfaces
- [x] - isc-dhcp-client-cwy2
- [x] - fixes only in debian control file (Provides/Breaks: isc-dhcp-client)

**Comment by relet** [comment]
Inventory sensor has timeout issues (currently set to 1s timeout in order not to block metadata-exporter)

**Comment by relet** [comment]
Done, ready to exit staging on Wed, March 7

**Comment by jonakarl** [comment]
Sorry for the late reply but is it still possible to add : 
* libguestfs-tools
* qemu-kvm

Those two packages are the reason for isc-dhcp-client-cwy2 but must have slipped under the radar.

**Comment by relet** [comment]
Without the scripts to use these, I don't think we need to add extra packages. But we need to have the cwy2 package in the repositories for the others to be installable at all.

**Comment by jonakarl** [comment]
Ok sure as long as the lead time to install the packages after the scripts are finished does not pose a problem.
