### ISSUE TITLE
Installation issues with KAU node shipment nodes 11-40

### ISSUE THREAD

**Issue by alfs** [MONROE-PROJECT/Maintenance#14]
Telenor subscriptions are now activated, and all but 2 nodes
of the 30 new are active inventory (#237 and #241) after multiple power cycles and modem reboots. 

Most nodes have a green or red management interface, but celerway
please have a look at #250, #251, since these report Modem (unknown) for
the management interface - it could be that subscriptions are not
activated for some reason here (or could be coverage) but if you can
check the logs we can do some further fixing here.

Could also be good to check that all nodes that have contacted
the inventory also managed to update successfully.

**Comment by kristrev** [comment]
**250**

There are three modems with issues.

The internal modem can't attach to the network, indicating a subscription issue. Restarting modem did not help.

usb1 failed to get an IP address (using DHCP). No error in kernel logs. Neither restarting multi nor running ifdown/ifup manually helped.

usb 2 (ICCID 89460120151127090161) is PIN locked.

**251**

Is unreachable from the remote server for the time beeing.

**Comment by relet** [comment]
@alfs: Can you check ICCID 89460850007006592394 is actually unlocked? It still shows "Telenor/no network". The other Telenor mifi in #250 looks ok. 

If you can tell me the IMEI for usb1 (the 3 mifi), I can see if I can reach it via wifi.

**Comment by alfs** [comment]
@jonakarl node 250 has internal iccid 89460850007006592394. This was not included in the Telenor subscription activation mail. Didn't find a similar ICCID in your subscription activation mail.

Node 251 has internal iccid 50007006922013. The Telenor order page lists 50007006222013 (62 instead of 69), so a typo.

@relet IMEIs are 89460850007007787449, 864154026015875 and 864154026017491

**Comment by alfs** [comment]
During the evening I have removed the PIN codes from the Telia sim cards, so all subscriptions should be active unless there's some typo.

Thinks to look at:

104 - something strange in the inventory (seeing a WIND (Blu) interface). Modems and node is rebooted, and cables wiggled, still only management green, mifis are grey

234 has a grey interface (Telia mifi)

237 is not reporting at all - need to be checked with a serial console. APU has a green LED and modems have connectivity. Maybe bios-boot issue.

238 has problem with the SMS socket. It worked for some time, but then it blocked power. Need to try the reset pin procedure posted by Audun to the monroe-list 1-2 weeks ago. For now, I've bypassed the SMS socket.

241 is missing the management interface - @jonakarl another wrong SIM #, cant find 50007006921965 in your Telenor activation mail. 

250, 251, see above (mgmt subs not activated)

93 - two gray interfaces (Telenor and 3).

Overall, there are many red or orange interfaces. I guess this can be due to low signal strength or coverage. Currently the 30 nodes are all placed in the same room (for testing) so 150 modems (30*(3 mifi + 1 mgmt + 1 socket)) in that small area may be too much.

**Comment by relet** [comment]
I had a quick look, also enabling the nodes that were all green for
scheduling and base experiments.

> 104 - something strange in the inventory (seeing a WIND (Blu) interface).
> Modems and node is rebooted, and cables wiggled, still only management
> green, mifis are grey
> 
> No mifis in lsusb, power/hardware issues and error -32 in dmesg
> 
> 234 has a grey interface (Telia mifi)
> 
> Power/hardware issues, error -32 in dmesg

235 does not seem to have any SIM set in, is that correct?

> 241 is missing the management interface - @jonakarl
> https://github.com/jonakarl another wrong SIM #, cant find
> 50007006921965 in your Telenor activation mail.
> 
> Probably. It also looks like the 3 SIM is missing?
> 
> 93 - two gray interfaces (Telenor and 3).
> 
> power/hardware issues, error -32

**Comment by jonakarl** [comment]
@relet @alfs There where some typos unfortunately  so far I have sent the following corrected ICCIDs to Telenor: 
50007006592394 (node 250, Management) 
50007006922013 (node 251, Management) 
50007007787423 (node 81, Modem)

I am also furthering investigating 50007006921695 (node 241, Managment) that Telenor could not activate for some reason

**Comment by jonakarl** [comment]
It was also a typo on (Node 241, management) so I have also sent ICCID 50007006921965 to Telenor for correction

**Comment by relet** [comment]
Can this be closed?

**Comment by jonakarl** [comment]
The nodes and subscriptions have been reassigned to other nodes/roles so this issue is not longer relevant.
