### ISSUE TITLE
[Node 31]  Problems with the usb interfaces

### ISSUE THREAD

**Issue by rmonno** [MONROE-PROJECT/Maintenance#19]
This morning I found the 3 usb interfaces gray. I rebooted the node through the GSM socket. The interfaces became green (2) and yellow (1). 
This afternoon the interfaces were gray again. A reboot solved the problem in the sense that now I have 3 red interfaces.

There aren't electrical problems in dmesg.

**Comment by realmobile** [comment]
I checked the log, and this an issue we have worked on today. It is caused by port or MiFi restart in Downstream port 1. 
We will look into a fix. So, do not spend energy on this one :)
