### ISSUE TITLE
[Node 46] Hardrive failure

### ISSUE THREAD

**Issue by jonakarl** [MONROE-PROJECT/Maintenance#20]
The node unexpectedly died and cannot boot anymore : 

Serial console output (when pressing F10 to get to the boot menu): 

PC Engines APU BIOS build date: Sep  8 2014
Total memory 4096 MB
AMD G-T40E Processor
CPU MHz=1000
WARNING - Timeout at ehci_wait_td:517!
ehci pipe=0xdf103f80 cur=df103bc0 tok=80000d80 next=1 td=0xdf103bc0 status=80000d80
Initialized USB HUB (0 ports used)

iPXE (http://ipxe.org) 00:00.0 C000 PCI2.10 PnP PMM+DF0D8E70+DF038E70 C000

Press F10 key now for boot menu:
Select boot device:
1. AHCI/0: PS3109S9 ATA-7 Hard-Disk (20 MiBytes)
2. iPXE (PCI 00:00.0)
3. Payload [setup]
4. Payload [memtest]

drive 0x000f2a80: PCHS=160/8/32 translation=none LCHS=160/8/32 s=40961
Booting from Hard Disk...
Boot failed: not a bootable disk

**Comment by kristrev** [comment]
What happens if you connect the HDD to another maching and set the boot flag/recreate MBR?

**Comment by jonakarl** [comment]
Discussion moved to  #35
