### ISSUE TITLE
[node 46] failed to pull base containers

### ISSUE THREAD

**Issue by relet** [MONROE-PROJECT/Maintenance#6]
Symptom: failed to register layer: rename /var/lib/docker/image/devicemapper/layerdb/tmp/layer-175460233 /var/lib/docker/image/devicemapper/layerdb/sha256/c025010844d837a02f61e1b05a134a100a690446dfaffc3335ec3c385af261e0: directory not empty

Resolution: reset /var/lib/docker

Root cause is unresolved.

**Comment by jonakarl** [comment]
Could be related to hardrive failure #35

**Comment by jonakarl** [comment]
Closing this and we can see if the problems reappers with fresh HDD.
