### ISSUE TITLE
[Node 199] The node is all Gray

### ISSUE THREAD

**Issue by ali-safari** [MONROE-PROJECT/Maintenance#63]
Node #199 restarted couple of times and modems' battery being drained but it is not GREEN yet.
Is there any other instructions to follow ?

**Comment by rmonno** [comment]
The node has now:
lsusb shows 2 ZTEs (usb0, usb1) that are working properly.

No wwan0 and usb2.

**Comment by ali-safari** [comment]
One of the ZTE modem is off completely, I tried to charged with another cable on my pc. it is not turning on! tried to reset but it isn't responding.
Is there any other test to do?
