### ISSUE TITLE
PIN lock for [Nodes #37,#40,#199]

### ISSUE THREAD

**Issue by ali-safari** [MONROE-PROJECT/Maintenance#7]
The TIM Sim card in these nodes have the wrong ICCID in DB.
need to updated the ICCID in DB #

**Comment by relet** [comment]
Analysis: 
The PIN numbers in the database (both monroe-production and docker-experiments branches) are correct and the mifis are now working. The original issue was that the PIN are printed with three zeroes on the SIM card, but reported with four zeroes by the hardware. The correct entry was added to the database earlier. 
The correct file was on the node, but the database contained only an earlier entry from before the patch. Why the file was not imported is unclear.
