### ISSUE TITLE
[NODE 68] ssh tunnel seems to be not stable

### ISSUE THREAD

**Issue by rmonno** [MONROE-PROJECT/Maintenance#81]
rmonno@MonroeSshp:~$ sshr-monroe 68
ssh: connect to host localhost port 10068: Connection refused
rmonno@MonroeSshp:~$ sshr-monroe 68
Warning: Permanently added '[localhost]:10068' (ECDSA) to the list of known hosts.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Nov  3 09:01:24 2016 from localhost
monroe@Monroe000db9400998:~$ Connection to localhost closed by remote host.
Connection to localhost closed.

It seems the node is rebooting periodically in short intervals. Or maybe the ssh-tunnel is not stable enough ?

**Comment by relet** [comment]
You can check the reboot log with
tuptime -t
It is rebooting, but probably not as quickly as you are thinking of.

11/02/2016   BAD              4 hours, 5 minutes and 22 seconds
1882   01:50:24 AM 11/03/2016             34 minutes and 38 seconds
02:25:02 AM 11/03/2016   BAD             2 hours, 38 minutes and 28 seconds
1883   05:03:30 AM 11/03/2016             51 minutes and 32 seconds
05:55:02 AM 11/03/2016   BAD                        1 minute and 29 seconds
1884   05:56:31 AM 11/03/2016     2 hours, 8 minutes and 31 seconds
08:05:02 AM 11/03/2016   BAD                       14 minutes and 3 seconds
1885   08:19:05 AM 11/03/2016     1 hour, 26 minutes and 29 seconds
