### ISSUE TITLE
Node hangs

### ISSUE THREAD

**Issue by alfs** [MONROE-PROJECT/Maintenance#9]
One common problem at KAU is that stationary nodes in our lab hangs every now and then (1-2 nodes per week). They turn fully grey in the inventory, does not respond on the serial console, but the APU shows a green light meaning that the unit is powered.

For example, see the monroe list thread 'State of KAU/Sweden nodes' to the monroe email list during july-aug 2016.

This issue-thread is meant to report these issues and have a collection of the maintenenace actions (typically rebooting). The ten kau nodes currently online are wired with the SIM power socket, so reboots should be possible by sms commands.

**Comment by alfs** [comment]
#50 is down. Last seen Fri Sep 02 2016 12:17:37 GMT+0200
#51 is down. Last seen Mon Sep 05 2016 15:39:40 GMT+0200

**Comment by jonakarl** [comment]
Can this be closed ?
